# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACLRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('containerHash', models.TextField(primary_key=True, serialize=False)),
                ('objectHash', models.TextField(db_index=True)),
                ('containerSig', models.TextField(max_length=2000)),
                ('objectContainerPath', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageHash', models.TextField(primary_key=True, serialize=False)),
                ('messageType', models.IntegerField()),
                ('messageSig', models.TextField(blank=True, max_length=2000)),
                ('dossierHash', models.TextField()),
                ('bodyHash', models.TextField()),
                ('messagePath', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('containers', models.ManyToManyField(related_name='messages', to='API.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('address', models.TextField(primary_key=True, serialize=False)),
                ('pubkey', models.TextField(unique=True)),
                ('nickname', models.TextField(unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaltedMetaHash',
            fields=[
                ('saltedMetaHash', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_messages', to='API.Persona'),
        ),
        migrations.AddField(
            model_name='container',
            name='saltedMetaHashes',
            field=models.ManyToManyField(related_name='containers', to='API.SaltedMetaHash'),
        ),
        migrations.AddField(
            model_name='aclrule',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='API.Message'),
        ),
        migrations.AddField(
            model_name='aclrule',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='API.Persona'),
        ),
    ]
