# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('key', models.TextField()),
                ('used', models.BooleanField(default=False)),
                ('sender', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Invitation')),
            ],
        ),
    ]
