# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerHash', models.TextField(db_index=True)),
                ('objectHash', models.TextField(db_index=True)),
                ('containerSig', models.TextField()),
                ('objectContainerPath', models.TextField()),
                ('retainUntil', models.TextField(max_length=1000)),
                ('validUntil', models.TextField(max_length=1000)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='API.Message')),
            ],
        ),
        migrations.CreateModel(
            name='SaltedMetaHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaHash', models.TextField(db_index=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saltedMetaHashes', to='API.Container')),
            ],
        ),
    ]
