# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='containerSig',
            new_name='containerSign',
        ),
    ]
