# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
