# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_backup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='content',
            new_name='hash',
        ),
    ]
