# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_message_messagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageSig',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='container',
            name='containerSig',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='container',
            name='retainUntil',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='container',
            name='validUntil',
            field=models.TextField(max_length=2000),
        ),
    ]
