# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20180113_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='acl',
        ),
        migrations.AlterField(
            model_name='aclrule',
            name='key',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='aclrule',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl', to='API.Message'),
        ),
        migrations.AlterField(
            model_name='aclrule',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to='API.Persona'),
        ),
    ]
