# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20180113_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saltedmetahash',
            old_name='metaHash',
            new_name='saltedMetaHash',
        ),
    ]
