# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20180113_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='retainUntil',
        ),
        migrations.RemoveField(
            model_name='container',
            name='validUntil',
        ),
    ]
