# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20180115_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='id',
        ),
        migrations.RemoveField(
            model_name='container',
            name='message',
        ),
        migrations.RemoveField(
            model_name='saltedmetahash',
            name='container',
        ),
        migrations.RemoveField(
            model_name='saltedmetahash',
            name='id',
        ),
        migrations.AddField(
            model_name='container',
            name='saltedMetaHashes',
            field=models.ManyToManyField(related_name='containers', to='API.SaltedMetaHash'),
        ),
        migrations.AddField(
            model_name='message',
            name='containers',
            field=models.ManyToManyField(related_name='messages', to='API.Container'),
        ),
        migrations.AlterField(
            model_name='container',
            name='containerHash',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saltedmetahash',
            name='saltedMetaHash',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
