# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20180115_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
