import graphene

class BodyType(graphene.Enum):
    CHECKPOINT = '00'
    '''Audit checkpoint records'''
    INVITATION = '10'
    '''Invite new participant'''
    REGISTRATION = '11'
    '''Register persona'''
    DELEGATION = '12'
    '''Delegate existing persona'''
    BACKUP = '13'
    '''Key Recovery Vault'''
    RECOVER = '14'
    '''Key Recovery Request'''
    DIRECT_ATTESTATION = '30'
    '''Provide attestation to subject'''
    VERIFICATION_REQUEST = '31'
    '''Request source object review'''
    SERVICE_OFFERING = '40'
    '''Offer service'''
    SERVICE_REQUEST = '41'
    '''Provide dossier for service'''
    AMENDMENT_REQUEST = '42'
    '''Request ad-hoc dossier addition'''
    DELEGATION = '50'
    '''Delegation'''
    VALIDATION = '51'
    '''Validation'''
